### ISSUE TITLE
Needs moar cowbell

### ISSUE THREAD

**Issue by johndbritton** [johndbritton/taiwan#1]
There's a real lack of cowbell in this project

:cow: :bell: 

@muan Maybe you can help?

**Comment by muan** [comment]
:cow::cow::cow::cow::cow::cow::cow::cow::cow::cow::cow::cow::cow:
:cow::cow::cow::cow::cow::bell::bell::bell::cow::cow::cow::cow::cow:
:cow::cow::cow::cow::cow::bell::cow::bell::cow::cow::cow::cow::cow:
:cow::cow::cow::cow::cow::bell::bell::bell::cow::cow::cow::cow::cow:
:cow::cow::cow::cow::bell::bell::bell::bell::bell::cow::cow::cow::cow:
:cow::cow::cow::cow::bell::bell::bell::bell::bell::cow::cow::cow::cow:
:cow::cow::cow::bell::bell::bell::bell::bell::bell::bell::cow::cow::cow:
:cow::cow::cow::bell::bell::bell::bell::bell::bell::bell::cow::cow::cow:
:cow::cow::cow::bell::bell::bell::bell::bell::bell::bell::cow::cow::cow:
:cow::cow::bell::bell::bell::bell::bell::bell::bell::bell::bell::cow::cow:
:cow::bell::bell::bell::bell::bell::bell::bell::bell::bell::bell::bell::cow:
:cow::cow::bell::bell::bell::bell::bell::bell::bell::bell::cow::cow::cow:
:cow::cow::cow::cow::cow::cow::bell::cow::cow::cow::cow::cow::cow:
:cow::cow::cow::cow::cow::cow::cow::cow::cow::cow::cow::cow::cow:
